In [1]:
print("hello world")

hello world


In [29]:
import numpy as np


import matplotlib.pyplot as mp

import pandas as pd

#fetching data
data = pd.read_csv("Data.csv",encoding='utf-8')
inp = data.iloc[:,:-1].values
out= data.iloc[:,-1].values


from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

'''
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer = imputer.fit(inp[:,1:3])
inp[:,1:3]=imputer.transform(inp[:,1:3])


#encode categorical data

transformer = ColumnTransformer([("Country",OneHotEncoder(),[0])],remainder = 'passthrough')
inp = transformer.fit_transform(inp)                             





temp = LabelEncoder()
temp = temp.fit_transform(out)
out = temp


'''
#splitting data set into train and test

from sklearn.model_selection import train_test_split

inp_train,inp_test,out_train,out_test = train_test_split(inp,out,test_size = 0.2, random_state = 0)

print(inp_train)

from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
inp_train = SC.fit_transform(inp_train)
inp_test = SC.transform(inp_test)

print(inp_train)


[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
